kind: Service
apiVersion: v1
metadata:
  name: greenhouse-service
spec:
  selector:
    app: greenhouse
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      Nodeport:
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-greenhouse
  labels:
    app: greenhouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greenhouse
  template:
    metadata:
      labels:
        app: greenhouse
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: maven
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        volumeMounts:
          - name: host-time
            mountPath: /etc/localtime
            readOnly: true
          volumes:
          - name: host-time
    hostPath:
      path: /etc/localtime
        - containerPort: 8080
